server:
  port: 9005
spring:
  ##########################  druid配置   ##########################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://locaclhost:3306/xiaoyuanboke?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: root
      password: root
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
  profiles:
    active: common
    include: tencent
  mvc:
    static-path-pattern: /static/**
  redis:
    port: 6379
    host: localhost
    password: root
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    # 打印SQL语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      table-prefix: xy_
  type-aliases-package: com.xiaoyuan.front.db.entity
logging:
  level:
    com.shyroke.mapper: info