spring:
  mail:
    host: smtp.qq.com
    username: QQ邮箱
    password: 密钥
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
