eureka:
  client:
    service-url:
      # 注册到服务中
      defaultZone: http://localhost:9000/eureka/

spring:
##########################  druid配置   ##########################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/xiaoyuanboke?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
      username: xiaoyuan
      password: root
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 1200
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 25000
      validation-query: SELECT 'x'
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
  redis:
    port: 6379
    host: localhost
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    notice-virtual-host: notice-host
    virtual-host: /

# Sa-Token配置
sa-token:
  # token 名称 (同时也是cookie名称)
  token-name: token
  # token 有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token 临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uid
  # 是否输出操作日志
  is-log: false

wx:
  appId: xxxx
  appSecret: xxx
  callbackUrl: http://localhost:9004/back/api/system/wx_callback
  phoneBindingUrl: http://localhost:9528/#/phone
  loginUrl: http://localhost:9528/#/login
  homeUrl: http://localhost:9528/#/home
